### ISSUE TITLE
Race condition encountered: attempted to load session[SESSION_ID] which has been created but not yet serialized.

### ISSUE THREAD

**Issue by joeyzhu0422** [jcoleman/tomcat-redis-session-manager#30]
Sorry, I don't know how to use currentSession.manager.save(currentSession), I use (org.apache.catalina.Session) request.getSession()).getManager(), but request.getSession() is StandardSessionFacade, StandardSessionFacade could not getManager().

**Comment by asundaram** [comment]
We are getting this error in Production while using Tomcat 6 version of the redis session manager. Since  saveOnChange feature doesn't exist in this branch, we cannot use it (unfortunate). We would like to know what impact this exception has to the users. 

In New Relic we see transactions with these errors have a 200 HTTP response code. Does this mean that the user did not receive errors(maybe because of a retry somewhere)? Also there are 100's of such errors everyday in our logs but haven't heard any issues reported from our users or testers. 

Please advice.
