### ISSUE TITLE
Unable to use tomcat redis session manager latest version on tomcat 7

### ISSUE THREAD

**Issue by srividyak** [jcoleman/tomcat-redis-session-manager#66]
Hi James Coleman,

I have an application where I'm trying to use this session manager but upon starting tomcat, I get the following error: 

java.lang.VerifyError: Bad type on operand stack in method com.radiadesign.catalina.session.RedisSessionManager.initializeDatabaseConnection

Here are the libraries I've included under tomcat_home/lib:
1. commons-pool-1.6.jar
2. commons-pool2-2.2.jar
3. tomcat-redis-session-manager-1.2-tomcat-7.jar
4. jedis-2.5.2.jar

Am I missing any configuration?

**Comment by leonlau** [comment]
me too

**Comment by jcoleman** [comment]
As I've noted in several previous issues, these errors aren't from the current version (which has the class package prefix com.orangefunction rather than com.radiadesign).

You need to compile master; I no longer offer precompiled downloads of the latest version.

Your version is no longer supported.
